/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsJiraRouteImport } from './routes/settings.jira'
import { Route as IssuesKeyRouteImport } from './routes/issues.$key'
import { Route as AdminSyncRouteImport } from './routes/admin.sync'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsJiraRoute = SettingsJiraRouteImport.update({
  id: '/settings/jira',
  path: '/settings/jira',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesKeyRoute = IssuesKeyRouteImport.update({
  id: '/issues/$key',
  path: '/issues/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSyncRoute = AdminSyncRouteImport.update({
  id: '/admin/sync',
  path: '/admin/sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kanban': typeof KanbanRoute
  '/login': typeof LoginRoute
  '/timeline': typeof TimelineRoute
  '/admin/sync': typeof AdminSyncRoute
  '/issues/$key': typeof IssuesKeyRoute
  '/settings/jira': typeof SettingsJiraRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kanban': typeof KanbanRoute
  '/login': typeof LoginRoute
  '/timeline': typeof TimelineRoute
  '/admin/sync': typeof AdminSyncRoute
  '/issues/$key': typeof IssuesKeyRoute
  '/settings/jira': typeof SettingsJiraRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kanban': typeof KanbanRoute
  '/login': typeof LoginRoute
  '/timeline': typeof TimelineRoute
  '/admin/sync': typeof AdminSyncRoute
  '/issues/$key': typeof IssuesKeyRoute
  '/settings/jira': typeof SettingsJiraRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kanban'
    | '/login'
    | '/timeline'
    | '/admin/sync'
    | '/issues/$key'
    | '/settings/jira'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kanban'
    | '/login'
    | '/timeline'
    | '/admin/sync'
    | '/issues/$key'
    | '/settings/jira'
  id:
    | '__root__'
    | '/'
    | '/kanban'
    | '/login'
    | '/timeline'
    | '/admin/sync'
    | '/issues/$key'
    | '/settings/jira'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KanbanRoute: typeof KanbanRoute
  LoginRoute: typeof LoginRoute
  TimelineRoute: typeof TimelineRoute
  AdminSyncRoute: typeof AdminSyncRoute
  IssuesKeyRoute: typeof IssuesKeyRoute
  SettingsJiraRoute: typeof SettingsJiraRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/jira': {
      id: '/settings/jira'
      path: '/settings/jira'
      fullPath: '/settings/jira'
      preLoaderRoute: typeof SettingsJiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/$key': {
      id: '/issues/$key'
      path: '/issues/$key'
      fullPath: '/issues/$key'
      preLoaderRoute: typeof IssuesKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sync': {
      id: '/admin/sync'
      path: '/admin/sync'
      fullPath: '/admin/sync'
      preLoaderRoute: typeof AdminSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KanbanRoute: KanbanRoute,
  LoginRoute: LoginRoute,
  TimelineRoute: TimelineRoute,
  AdminSyncRoute: AdminSyncRoute,
  IssuesKeyRoute: IssuesKeyRoute,
  SettingsJiraRoute: SettingsJiraRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
